incubation project to readme.md added
TBD54566975/.github pull request #8
Opened 2023-10-13 03:29 UTC by Pratham271

Added the incubation please check.

2023-10-13 17:46 UTC, EbonyLouis commented
Also there should only be one file in this PR what is the second file? please remove it

2023-10-13 17:53 UTC, Pratham271 commented
Deleted the file, please check now.

2023-10-13 17:54 UTC, EbonyLouis commented
it's gone thanks! so now it's just addressing the readme changes

2023-10-23 16:29 UTC, EbonyLouis commented
@Pratham271 Hey just checking in do you need any help with the changes I requested? we can work on it together

2023-10-23 17:14 UTC, Pratham271 commented
Can you please tell me the changes that you requested, I think I didn't recieve them

2023-10-25 17:49 UTC, Pratham271 commented
I wanted to know if there is any update regarding this issue

2023-10-27 16:51 UTC, EbonyLouis commented
@Pratham271 in the requested code change, I commented above and tagged you. Where you added the project isn't where I need it to be. If you look at the requested changed above you will see it

2023-10-27 16:59 UTC, Pratham271 commented
Okay I'll fix that one sorry for the delay

2023-10-28 02:10 UTC, Pratham271 commented
I have made the changes now please check

2023-10-30 13:22 UTC, EbonyLouis commented
@Pratham271 thank you for the changes it's almost done 🥳. I added just a few things for you to change you can find them in the requested changes in the code review.

2023-10-31 14:55 UTC, EbonyLouis requested changes
Delete this file  `.DS_Store`

2023-10-31 14:55 UTC, EbonyLouis commented on profile/README.md
> +| [tbDEX](https://developer.tbd.website/projects/tbdex)  | [Web5](https://developer.tbd.website/projects/web5) | [tbLEND](https://discord.gg/bS59ANWc) |
@Pratham271 Thank you for working on this I think I confused you with my wording on the issue. Apologies right now you have tbLEND under our projects but it needs to go under incubation projects. So it should say 
`We also have two incubation projects with community member project leads` . 

In the picture below I want `tbLEND` to be right next to `Credential Selector`, it should be to the right of it in that chart. Does that make sense? 

<img width="1110" alt="Screenshot 2023-10-13 at 1 38 05 PM" src="https://github.com/TBD54566975/.github/assets/55366651/847b2e58-3a2c-40ae-9075-042dc678503c">

Also they now have a GitHub so when you add a link to the name please use this link instead: https://github.com/TBD54566975/incubation-tblend

2023-10-31 14:55 UTC, EbonyLouis commented on profile/README.md
> +| [tbDEX](https://developer.tbd.website/projects/tbdex)  | [Web5](https://developer.tbd.website/projects/web5) | [tbLEND](https://discord.gg/bS59ANWc) |
@Pratham271 hey it's what i wrote above, tbLEND needs to be next to Credential Selector in that chart

2023-10-31 14:55 UTC, EbonyLouis commented on profile/README.md
> +We currently have three main projects, each project has their components:
@Pratham271 please put this back to "two main projects"

2023-10-31 14:55 UTC, EbonyLouis commented on profile/README.md
> +| [Credential Selector](https://github.com/TBD54566975/incubation-verifiable-credential-selector)  | [tbLEND](https://discord.gg/bS59ANWc) |
thank you this is exactly where I wanted the new project 🥳

1. On **line 16** please change it from "one incubation project" to "two incubation projects with community member project leads:"
2. on **line 17** you have tbLEND linking to the Discord please link it to the GitHub repo, this is the url "https://github.com/TBD54566975/incubation-tblend#web5service"

2023-10-31 14:55 UTC, EbonyLouis commented on profile/README.md
> +<!-- Components: [Decentralized Web Node](https://github.com/TBD54566975/dwn-sdk-js#readme), [Decentralized Identifiers](https://w3c.github.io/did-core/), [Self-Sovereign Identity](https://github.com
**Line 21** can you delete this please

2023-10-31 14:55 UTC, EbonyLouis commented on profile/README.md
> +| Developers embed the VCS into their application to allow users to select and retrieve Verifiable Credentials (VCs) Project Lead: @jacksophtron | Connects the lender and borrower to exchange money s
Please change tbLEND's description to this: 
"A protocol that connects the lender and borrower to exchange money securely. To learn more about their project you can get started by watching this short [project overview](https://photos.onedrive.com/share/177DEE71378DB3AD!9886?cid=177DEE71378DB3AD&resId=177DEE71378DB3AD!9886&authkey=!APppAVFUzYZ2LIY&ithint=video&e=fddgt9). Project Lead: @ianpatton"

2023-11-01 02:05 UTC, Pratham271 commented
Hi @EbonyLouis please check now

2023-11-01 16:14 UTC, EbonyLouis commented
> Hi @EbonyLouis please check now
I left a comment, the file is still apart of this PR @Pratham271

2023-11-01 16:31 UTC, Pratham271 commented
Now the file is not included

2023-11-01 17:27 UTC, EbonyLouis commented
Thank you soo much ! great work! @Pratham271

2023-11-01 17:28 UTC, EbonyLouis approved these changes

2023-11-01 17:28 UTC, EbonyLouis commented on .DS_Store
@Pratham271 the file is still here

2023-11-01 17:28 UTC, merged